apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: my-deployment
  namespace: default
spec:
  progressDeadlineSeconds: 3600
  replicas: 1
  selector:
    matchLabels:
      app: my-deployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
    
  template:
    metadata:
      labels:
        app: my-deployment
    spec:
      containers:
        - image: deepikakhannarbs/my-node-app:1.0
          imagePullPolicy: Always
          name: my-deployment
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: my-deployment
  labels:
    app: my-deployment
spec:
  type: LoadBalancer
  selector:
    app: my-deployment
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
